# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DirCopy.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DirCopy(object):
    def setupUi(self, DirCopy):
        DirCopy.setObjectName("DirCopy")
        DirCopy.setEnabled(True)
        DirCopy.resize(569, 451)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DirCopy.sizePolicy().hasHeightForWidth())
        DirCopy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        DirCopy.setFont(font)
        DirCopy.setMouseTracking(False)
        DirCopy.setTabletTracking(False)
        DirCopy.setFocusPolicy(QtCore.Qt.NoFocus)
        DirCopy.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        DirCopy.setWindowIcon(icon)
        self.formLayout = QtWidgets.QFormLayout(DirCopy)
        self.formLayout.setObjectName("formLayout")
        self.DirPathLabel = QtWidgets.QLabel(DirCopy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DirPathLabel.setFont(font)
        self.DirPathLabel.setObjectName("DirPathLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.DirPathLabel)
        self.DirPath = QtWidgets.QLineEdit(DirCopy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DirPath.sizePolicy().hasHeightForWidth())
        self.DirPath.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.DirPath.setFont(font)
        self.DirPath.setText("")
        self.DirPath.setReadOnly(True)
        self.DirPath.setObjectName("DirPath")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.DirPath)
        self.DirPathButton = QtWidgets.QPushButton(DirCopy)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.DirPathButton.sizePolicy().hasHeightForWidth())
        self.DirPathButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.DirPathButton.setFont(font)
        self.DirPathButton.setObjectName("DirPathButton")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.DirPathButton)
        self.checkBox = QtWidgets.QCheckBox(DirCopy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.checkBox)
        self.DirPathLabel_2 = QtWidgets.QLabel(DirCopy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DirPathLabel_2.setFont(font)
        self.DirPathLabel_2.setObjectName("DirPathLabel_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.DirPathLabel_2)
        self.AimsDirPath = QtWidgets.QLineEdit(DirCopy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.AimsDirPath.setFont(font)
        self.AimsDirPath.setText("")
        self.AimsDirPath.setReadOnly(True)
        self.AimsDirPath.setObjectName("AimsDirPath")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.AimsDirPath)
        self.AimsDirPathButton = QtWidgets.QPushButton(DirCopy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.AimsDirPathButton.setFont(font)
        self.AimsDirPathButton.setObjectName("AimsDirPathButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.AimsDirPathButton)
        self.RunButton = QtWidgets.QPushButton(DirCopy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.RunButton.setFont(font)
        self.RunButton.setObjectName("RunButton")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.RunButton)
        self.line = QtWidgets.QFrame(DirCopy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.DirPathLabel_3 = QtWidgets.QLabel(DirCopy)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.DirPathLabel_3.setFont(font)
        self.DirPathLabel_3.setObjectName("DirPathLabel_3")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.DirPathLabel_3)
        self.DirList = QtWidgets.QListWidget(DirCopy)
        self.DirList.setMouseTracking(False)
        self.DirList.setTabletTracking(False)
        self.DirList.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.DirList.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.DirList.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.DirList.setIconSize(QtCore.QSize(25, 25))
        self.DirList.setObjectName("DirList")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.DirList)
        self.progressBar = QtWidgets.QProgressBar(DirCopy)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.formLayout.setWidget(11, QtWidgets.QFormLayout.SpanningRole, self.progressBar)

        self.retranslateUi(DirCopy)
        QtCore.QMetaObject.connectSlotsByName(DirCopy)

    def retranslateUi(self, DirCopy):
        _translate = QtCore.QCoreApplication.translate
        DirCopy.setWindowTitle(_translate("DirCopy", "DirCopy"))
        self.DirPathLabel.setText(_translate("DirCopy", "資料夾路徑："))
        self.DirPathButton.setText(_translate("DirCopy", "選擇資料夾"))
        self.checkBox.setText(_translate("DirCopy", "包含所有子資料夾"))
        self.DirPathLabel_2.setText(_translate("DirCopy", "目的地路徑："))
        self.AimsDirPathButton.setText(_translate("DirCopy", "選擇資料夾"))
        self.RunButton.setText(_translate("DirCopy", "執行"))
        self.DirPathLabel_3.setText(_translate("DirCopy", "資料夾清單："))

